spring:
  security:
    oauth2:
      client:
        registration:
          microsoft:
            client-id: d2a196a1-2148-4500-9497-ca51107037da
            client-secret: 0tuLaOxwj0e5xGGdxp6418gSG9riHDL5FD5IqnzHs4w=
            authorization-grant-type: authorization_code
            redirect-uri-template: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: User.Read
            client-name: Microsoft
            client-alias: microsoft
        provider:
          microsoft:
            authorization-uri: https://login.microsoftonline.com/common/oauth2/authorize?resource=https://graph.microsoft.com/
            token-uri: https://login.microsoftonline.com/common/oauth2/token
            user-info-uri: https://graph.microsoft.com/v1.0/me
            user-name-attribute: id
            jwk-set-uri: https://login.microsoftonline.com/common/discovery/keys